### ISSUE TITLE
The questions and bug about snapp_prep.rb

### ISSUE THREAD

**Issue by xiaoyuanbrother** [mmatschiner/snapp_prep#1]
Hello 
I have recently run into a error while doing a divergence-time analysis which reads : 
 
Error 110 parsing the xml input file
validate and intialize error: null
Error detected about here:
  <beast>
      <run id='mcmc' spec='MCMC'>
          <state id='state'>
              <stateNode id='tree' spec='beast.util.TreeParser'>
java.lang.NullPointerException
	at beast.evolution.tree.Tree.initAndValidate(Unknown Source)
	at beast.util.TreeParser.initAndValidate(Unknown Source)
	at beast.util.XMLParser.initBEASTObjects(Unknown Source)
	at beast.util.XMLParser.parse(Unknown Source)
	at beast.util.XMLParser.parseFile(Unknown Source)
	at beast.app.BeastMCMC.parseArgs(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)

and then I used the **example data** you provided，but the problem still exists.
I am sorry to bother you, I hope that you can help me.
Thank you

**Comment by mmatschiner** [comment]
Hi,
I could not replicate this issue with the example data. Could you check the following?
- Is SNAPP installed? 
- Did you provide the starting tree from example.tre with option -s?

**Comment by xiaoyuanbrother** [comment]
Hi，
I used the 'ruby snapp_prep.rb -p example.phy -t example.spc.txt -c example.con.txt -s example.tre -x snapp.xml'  command and get the result of the attachment. 
[snapp.xml.txt](https://github.com/mmatschiner/snapp_prep/files/3360826/snapp.xml.txt)
**In order to upload I added '.txt'**.
I tried it on beast2.3 and beast2.5, but the same problem still exists.

**Comment by mmatschiner** [comment]
Thanks for specifying. This XML file works for me. Which BEAST version do you use? Is the CladeAge add-on installed?

**Comment by casett** [comment]
I am getting this error with beast 2.6.4 - I don't see a CladeAge add-on option .... Did anyone find a solution?

**Comment by mmatschiner** [comment]
To install CladeAge, you can use the BEAST2 PackageManager. Open BEAUti, and then click on "Manage Packages" in the "File" menu; that should open the PackageManager. There you can select to install the "CA" add-on package, which stands for CladeAge. But if you want to run snapp_prep.rb with the example data, you can also simply delete the line with the CladeAge constraint from file example.con.txt.
