### ISSUE TITLE
The time node is shown to be negative..

### ISSUE THREAD

**Issue by Maotingru** [mmatschiner/snapp_prep#4]
Hi, Thank you very much for your tutorial. I have a problem. After finishing the operation, I opened the merge tree with Figtree and found that the time nodes were all negative.

**Comment by mmatschiner** [comment]
Hi, which tutorial do you mean? That one: https://github.com/mmatschiner/tutorials/tree/master/divergence_time_estimation_with_snp_data ? If so, what do you mean with the "merge tree"?

**Comment by Maotingru** [comment]
Thank you for your answer, this problem has been solved, I set the wrong time scale in Figtree.By the way, how to  constrain the age of  mulpitle node? For example, in the tutorial on the previous website, "In addition, we could also constrain the first divergence among the species Neolamprologus brichardi ("neobri"), Neolamprologus Gracilis ("neogra"), Neolamprologus marunguensis (" Neomar "),And Neolamprologus olivaceus (" Neooli ") according to the results of this earlier analysis.”

**Comment by Maotingru** [comment]
Or how to set up an single internal time node (such as an internal time node for a sister group) The tutorial used the crown node to set the constrain.

**Comment by mmatschiner** [comment]
You just write two or more lines to the same constraint file, like this for example:

lognormal(0,6.2666,0.13)  crown astbur,altfas,telvit,neobri,neochi,neocra,neogra,neohel,neomar,neooli,neopul,neosav,neowal
lognormal(0,4.0,0.1)  crown altfas,telvit,neobri,neochi,neocra,neogra,neohel,neomar,neooli,neopul,neosav,neowal

With the second constraint you calibrate the age of the crown group of the clade comprising all species except altfas. Have a look here for example to learn about the meaning of crown group/stem group: https://www.researchgate.net/figure/The-stem-and-crown-group-concepts-showng-their-relationship-to-plesions-and-scions-cf_fig1_223465290

**Comment by Maotingru** [comment]
I seemly get the idea. So, in the tutorial above, if I would like to use the divergent points of Neocra and Neomar to set. Just keep this single line "lognormal(0,384,0.1) stem neocra,neomar" in the restricted file? Or I need a starting tree？

**Comment by mmatschiner** [comment]
A starting tree is only needed if BEAST would throw an error without a starting tree (see this tutorial: https://github.com/mmatschiner/tutorials/tree/master/divergence_time_estimation). If you want to constrain the divergence between Neocra and Neomar to around 384, use this:
lognormal(0,384,0.1) crown neocra,neomar
But if you want to constrain the divergence between the clade combining Neocra and Neomar and their most closely related lineage, then you need this:
lognormal(0,384,0.1) stem neocra,neomar
Do you work with a clade that you think has diverged 384 million years ago? If yes, then I would be surprised that you have a SNP matrix for it.

**Comment by Maotingru** [comment]
Thanks. I just forgot to add the decimal point...^ ^ I found that it was not feasible to specify only the internal divergent time node. A starting tree was needed, otherwise the BEAST would report an error..
