### ISSUE TITLE
NoMethodError when reading PHYLIP file

### ISSUE THREAD

**Issue by simone-says** [mmatschiner/snapp_prep#5]
I'm getting this error when trying to generate the SNAPP xml file: 

`Traceback (most recent call last):
	2: from snapp_prep.rb:141:in `<main>'
	1: from snapp_prep.rb:141:in `each'
snapp_prep.rb:144:in `block in <main>': undefined method `upcase' for nil:NilClass (NoMethodError)
Did you mean?  case`

I'm running my data using these options:

`ruby snapp_prep.rb -p All_Species_m0_CDS_edited_relaxed.phylip -t samples_table.txt -c sample.con.txt -x -m 100 -l 1000000`

**Comment by mmatschiner** [comment]
I'm not sure why you get that error. Somehow, a line of the phylip file is not as expected (with a sequence ID first and then a sequence). If you insert a line saying "puts l" before line 144, you should see what line causes it. Other than that, I guess you would need to share your phylip file (by email if you like) so I can figure out what's happenning.
